version: "3.8"
services:
    
    #Grafana
    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro     
      ports:
      - 3000:3000
      expose:
      - "3000"
      networks:
      - mynetwork
    
    #Nginx
    nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      networks:
      - mynetwork
      ports:
      - 8080:80 

    #MySQL
    mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
      networks:
      - mynetwork
      ports:
      - 3306:3306
      expose:
      - "3306"
    
    #Prometheus
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
      - 9090:9090
      expose:
      - "9090"  
      networks:
      - mynetwork
    
    #Exporter
    mysql-exporter:
      image: prom/mysqld-exporter
      container_name: mysql-exporter
      environment:
      - DATA_SOURCE_NAME= ${MYSQL_USER}:${MYSQL_PASSWORD}@(mysql:3306)
      ports:
      - 9104:9104
      expose:
      - "9104"
      networks:
      - mynetwork 

        
networks:
    mynetwork:
      driver: bridge   